### ISSUE TITLE
Using RTL the overlay opens in right side of the page 

### ISSUE THREAD

**Issue by shadikhani** [vaadin/vaadin-date-picker-flow#234] opened 2020-04-20 14:41 UTC
When using the RTL, the overlay of the DatePicker opens on the right side of the page.

```
@Route("test")
public class Test extends VerticalLayout {
    private DatePicker labelDatePicker = new DatePicker();
    private TextField textField = new TextField();
    public Test() {

        FormLayout formLayout = new FormLayout();

        UI.getCurrent().setDirection(Direction.RIGHT_TO_LEFT);
        LocalDate now = LocalDate.now();
        labelDatePicker.setValue(now);
        textField.setValue("test");

        formLayout.addFormItem(textField,"Test");
        formLayout.addFormItem(labelDatePicker,"Test");
        add(formLayout);


    }
}
```

**Comment by DiegoCardoso** [comment] 2020-04-22 06:23
This was a known issue which now is fixed at https://github.com/vaadin/vaadin-date-picker-flow/releases/tag/3.1.0.alpha2.

Closing as duplicate of https://github.com/vaadin/vaadin-date-picker/issues/710.

**Closed by DiegoCardoso** 2020-04-22 06:23 UTC
