### ISSUE TITLE
DatePicker Selects And Shows the Wrong Date (Version 1.0.6)

### ISSUE THREAD

**Issue by ugurdoksan** [vaadin/vaadin-date-picker-flow#128] opened 2018-09-01 10:32 UTC
The locale problem is solved but, when I select the date, it selects and shows the previous day in mobile browsers like Chrome or Safari.

For Example in TR Locale in version **1.0.6** :
I select: **08**.09.2018 (**8** September 2018)
It selects: **07**.09.2018 (**7** September 2018)

The code is the same with #116.

`dpStartDate = new DatePicker( "" ); 
dpStartDate.setPlaceholder( "Start Date" ); 
dpStartDate.setLocale( new Locale( "tr", "TR" ) );`

**Comment by mikotin** [comment] 2018-09-03 08:06
Hi, could you tell browser version you are using and timezone where you are?

And also - if possible - some sort of screen capture of opened date picking popup?

Couldn't repeat the problem with equipment I have.

**Comment by mikotin** [comment] 2018-09-03 08:37
@ugurdoksan thanks a lot! 

We'll try to reproduce the issue, I'll keep you informed.

**Comment by mikotin** [comment] 2018-09-03 10:43
Couldn't still reproduce the problem, @ugurdoksan , can you navigate to https://mikko.app.fi/date/ and verify that the problem occurs also in that, so that we know for sure the code?

There's just minimal code with your given example running there.

**Comment by ugurdoksan** [comment] 2018-09-03 11:26
3 Eyl 2018 Pzt, saat 13:43 tarihinde Mikko Salminen <
notifications@github.com> şunu yazdı:

**Comment by mikotin** [comment] 2018-09-03 11:32
Sorry, it seems like you last message is missing @ugurdoksan ?

**Comment by ugurdoksan** [comment] 2018-09-03 11:41
3 Eyl 2018 Pzt, saat 14:32 tarihinde Mikko Salminen <
notifications@github.com> şunu yazdı:

**Comment by mikotin** [comment] 2018-09-03 14:09
Thank you. So now it's up to us to replicate the set you're using in order to reproduce problem. We've tested with multiple mobile devices without getting such problem.

We'll keep you informed on issue.

**Comment by mikotin** [comment] 2018-09-07 10:18
@ugurdoksan cannot reproduce the problem (tested with multiple different devices + timezones / locales). And I have hard time even guessing the cause if it. 

But it also really bugs, that there's a "error" in the value, meaning that parsing of it would have failed. Does that component work if used differently, like not using any locale or different version or just the pure webcomponent ( https://vaadin.com/components/vaadin-date-picker/html-examples/date-picker-basic-demos )?

**Comment by ugurdoksan** [comment] 2018-09-07 11:04
7 Eyl 2018 Cum, saat 13:18 tarihinde Mikko Salminen <
notifications@github.com> şunu yazdı:

**Comment by mikotin** [comment] 2018-09-19 05:45
@ugurdoksan we cannot reproduce the problem. We've tried multiple possible devices and locales, but we can't get explained issue reproduced. 

At the moment we will close this issue as not reproducible. 

If you (or someone else) can get this same issue with another device - so that it is possible to mimic the same setting to get it reproduced - please open a ticket, or re-open this.

**Closed by mikotin** 2018-09-19 05:45 UTC
Labels: bug, components
