### ISSUE TITLE
Dates on first of January (starting from 1940 and years before) give 12/30/1939

### ISSUE THREAD

**Issue by michel-mercera** [vaadin/vaadin-date-picker-flow#189] opened 2019-06-28 08:54 UTC
### Description
When using the Java version of the date picker, selecting dates on the 16th of may 1940  and before the date picker returns the date of two days before so when entering 16th of may 1940 the date picker shows 5/14/1940. 

### Expected outcome
When selecting 1/01/1940 with the date picker the date picker should show 1/01/1940.

### Actual outcome
The date picker shows 12/30/1939.

### Live Demo
https://vaadin.com/components/vaadin-date-picker/java-examples

### Steps to reproduce
With Safari enter the date  1/01/1940 in the example page below:
https://vaadin.com/components/vaadin-date-picker/java-examples

### Browsers Affected

- [ ] Chrome
- [x] Firefox
- [x] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by Haprog** [comment] 2019-07-01 07:32
@michel-mercera Can you reproduce this on some version of Firefox (since you marked it in the description)? I tried, but can't reproduce this at least on Firefox 67.0.4 (64-bit) or Firefox 60.7.2esr (64-bit) on macOS 10.14.5.

This seems to be a duplicate of an older issue #126 which was originally reported only for Firefox.

**Comment by Haprog** [comment] 2019-07-03 06:27
I'm closing this as a duplicate of #126. Please continue the discussion there. I will copy most relevant info from here to a new comment in #126.

**Closed by Haprog** 2019-07-03 06:27 UTC
Labels: bug
